---

#- name: check if path to conflucence exist 
  #stat: 
    #path: "{{ installPath }}"
  #register: installdir

- name: check if path to conflucence exist 
  stat: 
    path: "{{ ln_destpath }}"
  register: ln_destpath

- name: create symlinc for install dir
  file:
    src: "{{ ln_path }}"
    dest: /opt/bitbucket/current
    #owner: root
    #group: root
    state: link

- name: permissions install dir
  file:
    path: "{{ installPath }}"
    state: directory
    owner: "{{ admin }}"
    group: "{{ admin }}"
    mode: 700
 
#- name: permissions install dir current
#  command: chown root:root "{{ installPath }}"

