---
- hosts: all
  remote_user: root
  #remote_user: root
  #become: yes
  #become_method: sudo

  tasks:
  #- name: upgrade all packages
    #apt:
      #name: '*'
      #state: latest

  #- name: upgrade all packages
  #  package:
  #    name: "*"
  #    state: latest


  - name: Install packages ubuntu
    package:
      name:
       # - cockpit
        - curl
        - wget
        - python
        - python3
        - python3-pip
        - git
        - vim
        - apt-utils
        #- device-mapper-persistent-data
        - lvm2
        - lynis
        - fail2ban
      state: present
    ignore_errors: yes

  - name: Install packages centos7 and RHEL7
    package:
      name:
        - cockpit
        #- podman
        - curl
        - wget
        - python
        - python3
        - python3-pip
        - git
        - vim
        - yum-utils
        #- device-mapper-persistent-data
        - lvm2
        - epel-release
        - sudo
        - bash-completion
        #- fail2ban
        #- centos-release-scl-rh
        #- centos-release-scl
      state: present
    ignore_errors: yes


  - name: Install packages centos7 and RHEL7
    package:
      name:
        - fail2ban
      state: present
    ignore_errors: yes

  - name: add group admins for nopasswd sudo
    group:
      name: admins
      state: present

  - name: sudoers file
    get_url:
      url: https://raw.githubusercontent.com/habbis/sudoers/master/admins
      dest: /etc/sudoers.d
      mode: '0440'

  - name: Download sshd_config from git repo
    get_url:
      url: https://gitlab.com/habbis/openssh_config/raw/master/sshd_config
      dest: /etc/ssh/
      mode: '0744'

  - name: allow ForwardAgent ssh_config for bastion server
    lineinfile:
      path: /etc/ssh/ssh_config
      regexp: 'ForwardAgent no'
      line: "ForwardAgent yes"

  - name: add right sftp server for rhel/centos in sshd_config
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '/usr/lib/openssh/sftp-server'
      line: "Subsystem  sftp /usr/libexec/openssh/sftp-server"
    #when: ansible_facts == "CentOS"
    when: ansible_pkg_mgr == "yum"


  - name: add right sftp server for rhel/centos in sshd_config
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '/usr/lib/openssh/sftp-server'
      line: "Subsystem  sftp /usr/libexec/openssh/sftp-server"
    #when: ansible_facts == "CentOS"
    when: ansible_pkg_mgr == "dnf"

  - name: Create group for docker
    group:
      name: docker
      state: absent

  - name: add user called user with sudo right
    user:
      name: user
      shell: /bin/bash
      groups: admins
      append: yes

  - name: set authorized keys from github to user
    authorized_key:
      user: user
      state: present
      key: https://github.com/habbis.keys

  - name: Create config file for fail2ban
    template:
      src: templates/jail.local
      dest: /etc/fail2ban/jail.local
      owner: root
      group: root
      mode: 0644

  - name:  enable_fail2ban
    systemd:
      name: fail2ban
      state: started
      enabled: yes

  - name: reload sshd
    service:
      name: sshd
      state: reloaded


   #- name: set authorized keys from github to virt
     #authorized_key:
       #user: virt
       #state: present
       #keys: https://github.com/habbis.keys


      #- name: enable cockpit systemd service
      #firewalld:
      #service: cockpit
      #permanent: yes
      #state: enabled
