- name: Create a virtual machine 01 on given ESXi hostname
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ datacenter_name }}"
    cluster "{{ cluster }}"
    folder:  "{{ folder }}"
    template: "{{ templateName01 }}"
    name: "{{ vmname1 }}"
    state: poweredon
    #guest_id: "{{ guestOS01 }}"
    disk:
    - size_gb: 32
      #type: thin
      type: thin
      datastore: "{{ datastore }}"
    - size_gb: 300
      type: thin
      #type: thick
      datastore: "{{ datastore }}"
    hardware:
      memory_mb: "{{ mram }}"
      num_cpus: "{{ mcpu }}"
      hotadd_cpu: True
      hotadd_memory: True
      scsi: paravirtual
    networks:
    - name: "{{ network }}"
      ip: "{{ vmip }}"
      gateway: "{{ nameserver }}"
      netmask: 255.255.255.0
      nameservers: "{{ nameserver }}"
      customization:
        hostname: "{{ vmname1 }}"
        #domain: "{{ domain }}"
        #dns_servers:
         #- "{{ nameserver }}"
         # - 1.1.1.1
    wait_for_ip_address: yes
  delegate_to: localhost
  register: deploy_vm
