---
- name: install telegraf debian/ubuntu
  apt:
    deb: "{{ influx_deb }}"
  when: ansible_pkg_mgr == "apt"

- name: install telegraf rehl7
  yum:
    name: "{{ influx_rhel }}"
    state: present
  when: ansible_pkg_mgr == "yum"

- name: install telegraf rhel8
  yum:
    name: "{{ influx_rhel }}"
    state: present
  when: ansible_pkg_mgr == "dnf"
