---
- name: install telegraf debian/ubuntu
  apt:
    deb: "{{ kapacitor_deb }}"
  when: ansible_pkg_mgr == "apt"

- name: install telegraf rehl7
  yum:
    name: "{{ kapacitor_rhel }}"
    state: present
  when: ansible_pkg_mgr == "yum"


- name: install telegraf rhel8
  yum:
    name: "{{ kapacitor_rhel }}"
    state: present
  when: ansible_pkg_mgr == "dnf"
