- name: Create a virtual machine to cluster
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ datacenter_name }}"
    cluster: "{{ cluster }}"
    resource_pool: "{{ pool }}"
    folder:  "{{ folder }}"
    template: "{{ templateName01 }}"
    name: "{{ vmname02 }}"
    #state: poweredon
    state: present
    #guest_id: "{{ guestOS01 }}"
    disk:
    - size_gb: 25
      #type: thin
      type: thin
      datastore: "{{ datastore }}"
    disk:
    - size_gb: 50
      type: thin
    #  type: thin
      datastore: "{{ datastore }}"
    #- size_gb: 300
    #  type: thin
      #type: thick
      #datastore: "{{ datastore }}"
    hardware:
      memory_mb: "{{ ram }}"
      num_cpus: "{{ cpu }}"
      hotadd_cpu: True
      hotadd_memory: True
      scsi: paravirtual
    networks:
    - name: "{{ network01 }}"
      type: dhcp
      #ip: "{{ vmip }}"
      #gateway: "{{ nameserver }}"
      #netmask: 255.255.255.0
      #nameservers: "{{ nameserver }}"
      customization:
        hostname: "{{ vmname02 }}"
        #domain: "{{ domain }}"
        #dns_servers:
         #- "{{ nameserver }}"
         # - 1.1.1.1
    wait_for_ip_address: yes
  delegate_to: localhost
  #register: deploy_vm
