---
- name: setup application
  gather_facts: yes
  hosts: all
  remote_user: root
  #remote_user: user
  #become: yes
  #become_method: sudo

  roles:
    - addUser
    - install_application
    - install_packages
    #- lvm 
    - symlink
    - service
    #- mysql
