---
- name: setup application
  gather_facts: yes
  hosts: all
  remote_user: root
  #remote_user: user
  #become: yes
  #become_method: sudo

  roles:
    - addUser
    - install_application
    - install_packages
    - lvm
    - symlink
    - service

#- name: setup database
#  gather_facts: yes
#  hosts: c7node1
#  remote_user: root
  #remote_user: user
  #become: yes
  #become_method: sudo

#  roles:
#    - mysql
