---

- name: Check if /dev/mapper/vg0-Opt exists
  stat:
    path: /dev/mapper/vg0-Opt
  register: vg_Opt

- name: extend if vg-Opt if it exist 
  lvol:
    vg: vg0
    lvg: Opt
    size: 5000
    resizefs: true
  #when: vg_Opt|bool == True
  when: vg_Opt.stat.exists == True

- name: check for filesytem info for to make lvm
  stat:
    path: /dev/sdb
  register: sdb_info

- name: Create a logical volume for storing application data
  lvol:
    vg: "{{ vgname }}"
    lv: "{{ lvname }}"
    size: "{{ lvsize }}"
  #when: sdb_info|bool == True
  when: sdb_info.stat.exists == True

- name: Create a filesystem for lvm volume
  filesystem:
      fstype: "{{ filesystem }}"
      dev: "{{ device }}"
      #resizefs: no 
      force: no 
      state: present
  #when: sdb_info|bool == True
  when: sdb_info.stat.exists == True

- name: Mount the volume 
  mount:
    path: "{{ device }}"
    src: "{{ dataPath }}"
    opts: defaults
    fstype: xfs
  #when: sdb_info|bool == True
  when: sdb_info.stat.exists == True

