---
- name: setup extra pacakge #for ubuntu/debian centos 
  vars_files:
    - vars.yml
  #include_vars:
     #dir: group_vars
  #gather_facts: no
  gather_facts: yes
  hosts: all
  remote_user: root
  #remote_user: user
  #become: yes
  #become_method: sudo

  roles:
    - put_script
    - run_script
    - add_sshkey
    - psql_conf
    #- lvm
