---
- hosts: all
  remote_user: root
  #remote_user: vagrant
  #remote_user: user
  #become: yes
  #become_method: sudo

  tasks:
  #- name: upgrade all packages
  #  package:
  #    name: "*"
  #    state: latest

  - name: Install packages ubuntu and debian
    package:
      name:
        #- cockpit
        - curl
        - wget
        - python
        - python3
        - python3-pip
        - git
        - vim
        - apt-utils
        - lvm2
      state: present
    ignore_errors: yes

  - name: add group admins for nopasswd sudo
    group:
      name: admins
      state: present

  - name: Install packages centos7 and RHEL7
    package:
      name:
        - cockpit
        #- podman
        - curl
        - wget
        - python2
        - python3
        - python3-pip
        - git
        - vim
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - epel-release
        - sudo
        - bash-completion
        #- centos-release-scl-rh
        #- centos-release-scl
      state: present
    #ignore_errors: yes
    when: ansible_pkg_mgr == "yum"

  - name: sudoers file
    get_url:
      url: https://raw.githubusercontent.com/habbis/sudoers/master/admins
      dest: /etc/sudoers.d/
      mode: '0440'

  - name: Download sshd_config from git repo
    get_url:
      url: https://gitlab.com/habbis/openssh_config/raw/master/sshd_config
      dest: /etc/ssh/
      mode: '0744'

  #- name: Create group for docker
    #group:
      #name: docker
      #state: absent

  - name: add right sftp server for rhel/centos in sshd_config
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '/usr/lib/openssh/sftp-server'
      line: "Subsystem  sftp /usr/libexec/openssh/sftp-server"
    #when: ansible_facts == "CentOS"
    when: ansible_pkg_mgr == "yum"

  - name: add user called user with sudo right
    user:
      name: user
      shell: /bin/bash
      groups: admins
      append: yes

  - name: set authorized keys from github to user
    authorized_key:
      user: user
      state: present
      key: https://github.com/habbis.keys
    ignore_errors: yes

  - name: set authorized keys from github to user
    authorized_key:
      user: root
      state: present
      key: https://github.com/habbis.keys
    ignore_errors: yes


  - name: reload sshd
    service:
      name: sshd
      state: reloaded


   #- name: set authorized keys from github to virt
     #authorized_key:
       #user: virt
       #state: present
       #keys: https://github.com/habbis.keys


      #- name: enable cockpit systemd service
      #firewalld:
      #service: cockpit
      #permanent: yes
      #state: enabled

  - name: Install prerequisites
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2' ,'software-properties-common']
      update_cache: yes
    when: ansible_pkg_mgr == "apt"

  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    when: ansible_pkg_mgr == "apt"

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
    when: ansible_pkg_mgr == "apt"

  - name: Add repository
    command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    when: ansible_pkg_mgr == "yum"

  - name: Install Docker
    apt:
      name: docker-ce
      update_cache: yes
    when: ansible_pkg_mgr == "apt"

  - name: install docker centos
    package:
      name: docker-ce
      state: present
    when: ansible_pkg_mgr == "yum"

  - name: Create group for docker
    group:
      name: docker
      state: present

  - name: add user called user with docker right
    user:
      name: cusr
      shell: /bin/bash
      groups: docker
      append: yes

  - name: Set authorized keys taken from url
    authorized_key:
      user: cusr
      state: present
      key: https://github.com/habbis.keys
    ignore_errors: yes

  - name: start and enable docker service
    service:
      name: docker
      enabled: yes
      state: started

  - name: Copy systl settings repo /etc/systctl.d/
    copy:
      src: templates/kubernetes.repo
      dest: /etc/yum.repos.d/kubernetes.repo
      owner: root
      group: root
      mode: u=rw,g=r,o=r
    when: ansible_pkg_mgr == "yum"

  - name: Copy kubernetes repo to yum.repos
    copy:
      src: templates/kubernetes.repo
      dest: /etc/yum.repos.d/kubernetes.repo
      owner: root
      group: root
      mode: u=rw,g=r,o=r
   when: ansible_pkg_mgr == "yum"

  - name: install docker centos
    package:
      name: 
        - kubeadm
        - kubelet
        - kubectl
      state: present
    when: ansible_pkg_mgr == "yum"

  - name: Remove  user 'root'
    command: passwd --lock root

  - name: Remove pass pasword for user 'root'
    command: passwd -d root

  - name: Remove  user 'root'
    command: passwd --lock root
