---
- hosts: localhost
  gather_facts: no
  #remote_user: root
  #remote_user: root
  #become: yes
  #become_method: sudo

  tasks:

  - name: snapshot of vm
    vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder:  "{{ folder }}"
      name: "{{ vmname01 }}"
      state: present
      snapshot_name: beforeInstall
      description: beforeInstall
      #state: absent
      #state: revert
      #state: remove_all
      #quiesce: yes
      memory_dump: yes
      #remove_children: yes
    delegate_to: localhost

  - name: snapshot of vm
    vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder:  "{{ folder }}"
      name: "{{ vmname01 }}"
      state: present
      snapshot_name: beforeInstall
      description: beforeInstall
      #state: absent
      #state: revert
      #state: remove_all
      #quiesce: yes
      memory_dump: yes
      #remove_children: yes
    delegate_to: localhost


  - name: snapshot of vm
    vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder:  "{{ folder }}"
      name: "{{ vmname02 }}"
      state: present
      snapshot_name: beforeInstall
      description: beforeInstall
      #state: absent
      #state: revert
      #state: remove_all
      #quiesce: yes
      memory_dump: yes
      #remove_children: yes
    delegate_to: localhost



  - name: snapshot of vm
    vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder:  "{{ folder }}"
      name: "{{ vmname03 }}"
      state: present
      snapshot_name: beforeInstall
      description: beforeInstall
      #state: absent
      #state: revert
      #state: remove_all
      #quiesce: yes
      memory_dump: yes
      #remove_children: yes
    delegate_to: localhost


  - name: snapshot of vm
    vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder:  "{{ folder }}"
      name: "{{ vmname02 }}"
      state: present
      snapshot_name: beforeInstall
      description: beforeInstall
      #state: absent
      #state: revert
      #state: remove_all
      #quiesce: yes
      memory_dump: yes
      #remove_children: yes
    delegate_to: localhost


  - name: snapshot of vm
    vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder:  "{{ folder }}"
      name: "{{ vmname04 }}"
      state: present
      snapshot_name: beforeInstall
      description: beforeInstall
      #state: absent
      #state: revert
      #state: remove_all
      #quiesce: yes
      memory_dump: yes
      #remove_children: yes
    delegate_to: localhost



  - name: snapshot of vm
    vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder:  "{{ folder }}"
      name: "{{ vmname05 }}"
      state: present
      snapshot_name: beforeInstall
      description: beforeInstall
      #state: absent
      #state: revert
      #state: remove_all
      #quiesce: yes
      memory_dump: yes
      #remove_children: yes
    delegate_to: localhost



  - name: snapshot of vm
    vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder:  "{{ folder }}"
      name: "{{ vmname06 }}"
      state: present
      snapshot_name: beforeInstall
      description: beforeInstall
      #state: absent
      #state: revert
      #state: remove_all
      #quiesce: yes
      memory_dump: yes
      #remove_children: yes
    delegate_to: localhost


  - name: snapshot of vm
    vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder:  "{{ folder }}"
      name: "{{ vmname07 }}"
      state: present
      snapshot_name: beforeInstall
      description: beforeInstall
      #state: absent
      #state: revert
      #state: remove_all
      #quiesce: yes
      memory_dump: yes
      #remove_children: yes
    delegate_to: localhost


  - name: snapshot of vm
    vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder:  "{{ folder }}"
      name: "{{ vmname08 }}"
      state: present
      snapshot_name: beforeInstall
      description: beforeInstall
      #state: absent
      #state: revert
      #state: remove_all
      #quiesce: yes
      memory_dump: yes
      #remove_children: yes
    delegate_to: localhost


  - name: snapshot of vm
    vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder:  "{{ folder }}"
      name: "{{ vmname09 }}"
      state: present
      snapshot_name: beforeInstall
      description: beforeInstall
      #state: absent
      #state: revert
      #state: remove_all
      #quiesce: yes
      memory_dump: yes
      #remove_children: yes
    delegate_to: localhost
