---
- hosts: localhost
  gather_facts: no
  #remote_user: root
  #remote_user: root
  #become: yes
  #become_method: sudo

  tasks:
  - name: vm snapshot
    vmware_guest_snapshot_info:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder:  "{{ folder }}"
      name: "{{ vmname01 }}"
    delegate_to: localhost
    register: snapshot_info